apiVersion: terraform.core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: s3-input-port
  annotations:
    definition.oam.dev/description: Terraform configuration for s3 input port
    type: terraform
spec:
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
  schematic:
    terraform:
      configuration: |
        provider "aws" {
          region = "eu-central-1"
        }
        
        resource "aws_s3_bucket" "this" {
          bucket = "input_bucket"
          tags = {
            Name = "data bucket"
            }
         }

        data "aws_caller_identity" "current" {}
